Loading Test Data...
Finished Loading Test Data.

Traceback (most recent call last):
  File "supervised_training.py", line 67, in <module>
    with open(f"{model_instance_directory}/log.csv", "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '../ModelInstances/predict5/log.csv'
